#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <SDL.h>
#include <string>
struct CollisionBox {
	int x, y, w, h;
};

const int SCREEN_WIDTH = 400,
SCREEN_HEIGHT = 500,
BG_HEIGHT = 750,
PLAYER_VEL = 8,
PLAYER_WIDTH = 50,
PLAYER_HEIGHT = 38,
SPCENEMY_W = 49,
SPCENEMY_H = 25,
SPCENEMY_S = 6,
UFO_RADIUS = 45,
CHARGE_DIST = 75,
LSR_CHARGEH = 56,
LSR_CHARGEW = 54,
LSR_H = 33,
LSR_W = 9,
LSR_SPEED = 15,
SPDLINE_W = 2,
SPDLINE_H = 53,
MAX_HEALTH = 100,
ARCADE_FONTSZ = 15,
SCROLL_SPEED = 5,
GAME_LIVES = 3,
DEATH_COUNTER = 1000;
enum bkgs { SCROLL1, SCROLL2 };
enum playerText { HEALTH, SCORE, SCORE_TEXT, LIVES, LIVES_TEXT, GAME_OVER, RETRY};
enum gameFont { ARCADE, ARCADE_LARGE };
enum playerArt { PLAYER, PLEFT, PRIGHT, PDAMAGED, LCHARGE, LSHOT, SPEED_LINE };
enum enemyArt { MAIN_SHIP, UFO };
enum gameEffects { LASER, COLLISION };
enum gameMusic { DEATH, SPACE_GUNNER};

#endif