#ifndef CONSTANTS_H
#define CONSTANTS_H

#include <SDL.h>
#include <string>
const int SCREEN_WIDTH = 600,
SCREEN_HEIGHT = 750,
BG_HEIGHT = 750,
PLAYER_VEL = 4,
PLAYER_WIDTH = 50,
PLAYER_HEIGHT = 38,
SPCENEMY_H = 25,
SPCENEMY_W = 49,
SPCENEMY_S = 10,
UFO_RADIUS = 45,
LSR_W = 9,
LSR_CHARGEH = 56,
LSR_CHARGEW = 54,
CHARGE_DIST = 75,
LSR_H = 33,
SPDLINE_W = 2,
SPDLINE_H = 53,
LSR_SPEED = 15,
MAX_HEALTH = 100,
ARCADE_FONTSZ = 15,
SCROLL_SPEED = 5;
enum bkgs { SCROLL1, SCROLL2 };
enum playerText { HEALTH, SCORE, SCORE_TEXT, LIVES, LIVES_TEXT};
enum gameFont { ARCADE };
enum playerArt { PLAYER, PLEFT, PRIGHT, PDAMAGED, LCHARGE, LSHOT, SPEED_LINE };
enum enemyArt { MAIN_SHIP, UFO };

#endif